apiVersion: apps/v1
kind: Deployment
metadata:
    name: toto-nodems-expenses-depl
    labels:
        microserice: toto-nodems-expenses
spec:
    replicas: 2
    selector:
        matchLabels:
            microservice: toto-nodems-expenses
    template:
        metadata:
            labels:
                microservice: toto-nodems-expenses
        spec:
            containers:
            - name: toto-nodems-expenses
              image: eu.gcr.io/toto-270718/toto-nodems-expenses
              ports:
              - containerPort: 8080
              volumeMounts:
                  - mountPath: /var/secrets/google
                    name: service-account-key-vol
              env:
                  - name: GOOGLE_APPLICATION_CREDENTIALS
                    value: /var/secrets/google/ms-key.json
                  - name: TOTO_ENV
                    valueFrom:
                        configMapKeyRef:
                            name: env-map
                            key: env
            volumes:
                - name: service-account-key-vol
                  secret:
                      secretName: ms-service-account-key