name: Build Microservice

on:
  push:
    branches: [ k8s ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Login to Dockerhub
      run: echo ${{secrets.DOCKERHUB_PSWD}} | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin

    - name: Build Docker image
      run: docker build . -t nicolasances/toto-nodems-expenses:1.$GITHUB_RUN_NUMBER

    - name: Push Docker image to Dockerhub 
      run: docker push nicolasances/toto-nodems-expenses:1.$GITHUB_RUN_NUMBER
